apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongodb-pvc

